HANZI_DB = {   '学': {   'initial': 'x',
             'final': 'ue',
             'pinyin': 'xue',
             'tone': 2,
             'splits': []},
    '马': {   'initial': 'm',
             'final': 'a',
             'pinyin': 'ma',
             'tone': 3,
             'splits': []},
    '衣': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 1,
             'splits': []},
    '一': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 1,
             'splits': []},
    '乙': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 3,
             'splits': []},
    '二': {   'initial': '-',
             'final': 'er',
             'pinyin': 'er',
             'tone': 4,
             'splits': []},
    '十': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 2,
             'splits': []},
    '丁': {   'initial': 'd',
             'final': 'ing',
             'pinyin': 'ding',
             'tone': 1,
             'splits': []},
    '厂': {   'initial': 'ch',
             'final': 'ang',
             'pinyin': 'chang',
             'tone': 3,
             'splits': []},
    '七': {   'initial': 'q',
             'final': 'i',
             'pinyin': 'qi',
             'tone': 1,
             'splits': []},
    '八': {   'initial': 'b',
             'final': 'a',
             'pinyin': 'ba',
             'tone': 1,
             'splits': []},
    '人': {   'initial': 'r',
             'final': 'en',
             'pinyin': 'ren',
             'tone': 2,
             'splits': []},
    '入': {   'initial': 'r',
             'final': 'u',
             'pinyin': 'ru',
             'tone': 4,
             'splits': []},
    '儿': {   'initial': '-',
             'final': 'er',
             'pinyin': 'er',
             'tone': 2,
             'splits': []},
    '匕': {   'initial': 'b',
             'final': 'i',
             'pinyin': 'bi',
             'tone': 3,
             'splits': []},
    '几': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 3,
             'splits': []},
    '九': {   'initial': 'j',
             'final': 'iou',
             'pinyin': 'jiu',
             'tone': 3,
             'splits': []},
    '刁': {   'initial': 'd',
             'final': 'iao',
             'pinyin': 'diao',
             'tone': 1,
             'splits': []},
    '刀': {   'initial': 'd',
             'final': 'ao',
             'pinyin': 'dao',
             'tone': 1,
             'splits': []},
    '力': {   'initial': 'l',
             'final': 'i',
             'pinyin': 'li',
             'tone': 4,
             'splits': []},
    '乃': {   'initial': 'n',
             'final': 'ai',
             'pinyin': 'nai',
             'tone': 3,
             'splits': []},
    '又': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 4,
             'splits': []},
    '三': {   'initial': 's',
             'final': 'an',
             'pinyin': 'san',
             'tone': 1,
             'splits': []},
    '于': {   'initial': '-',
             'final': 'ü',
             'pinyin': 'yu',
             'tone': 2,
             'splits': []},
    '亏': {   'initial': 'k',
             'final': 'uei',
             'pinyin': 'kui',
             'tone': 1,
             'splits': []},
    '工': {   'initial': 'g',
             'final': 'ong',
             'pinyin': 'gong',
             'tone': 1,
             'splits': []},
    '土': {   'initial': 't',
             'final': 'u',
             'pinyin': 'tu',
             'tone': 3,
             'splits': []},
    '士': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 4,
             'splits': []},
    '才': {   'initial': 'c',
             'final': 'ai',
             'pinyin': 'cai',
             'tone': 2,
             'splits': []},
    '下': {   'initial': 'x',
             'final': 'ia',
             'pinyin': 'xia',
             'tone': 4,
             'splits': []},
    '寸': {   'initial': 'c',
             'final': 'uen',
             'pinyin': 'cun',
             'tone': 4,
             'splits': []},
    '丈': {   'initial': 'zh',
             'final': 'ang',
             'pinyin': 'zhang',
             'tone': 4,
             'splits': []},
    '万': {   'initial': '-',
             'final': 'uan',
             'pinyin': 'wan',
             'tone': 4,
             'splits': []},
    '上': {   'initial': 'sh',
             'final': 'ang',
             'pinyin': 'shang',
             'tone': 4,
             'splits': []},
    '小': {   'initial': 'x',
             'final': 'iao',
             'pinyin': 'xiao',
             'tone': 3,
             'splits': []},
    '口': {   'initial': 'k',
             'final': 'ou',
             'pinyin': 'kou',
             'tone': 3,
             'splits': []},
    '山': {   'initial': 'sh',
             'final': 'an',
             'pinyin': 'shan',
             'tone': 1,
             'splits': []},
    '巾': {   'initial': 'j',
             'final': 'in',
             'pinyin': 'jin',
             'tone': 1,
             'splits': []},
    '千': {   'initial': 'q',
             'final': 'ian',
             'pinyin': 'qian',
             'tone': 1,
             'splits': []},
    '乞': {   'initial': 'q',
             'final': 'i',
             'pinyin': 'qi',
             'tone': 3,
             'splits': []},
    '川': {   'initial': 'ch',
             'final': 'uan',
             'pinyin': 'chuan',
             'tone': 1,
             'splits': []},
    '亿': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 4,
             'splits': []},
    '个': {   'initial': 'g',
             'final': 'e',
             'pinyin': 'ge',
             'tone': 4,
             'splits': []},
    '夕': {   'initial': 'x',
             'final': 'i',
             'pinyin': 'xi',
             'tone': 1,
             'splits': []},
    '久': {   'initial': 'j',
             'final': 'iou',
             'pinyin': 'jiu',
             'tone': 3,
             'splits': []},
    '勺': {   'initial': 'sh',
             'final': 'ao',
             'pinyin': 'shao',
             'tone': 2,
             'splits': []},
    '凡': {   'initial': 'f',
             'final': 'an',
             'pinyin': 'fan',
             'tone': 2,
             'splits': []},
    '丸': {   'initial': '-',
             'final': 'uan',
             'pinyin': 'wan',
             'tone': 2,
             'splits': []},
    '及': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 2,
             'splits': []},
    '广': {   'initial': 'g',
             'final': 'uang',
             'pinyin': 'guang',
             'tone': 3,
             'splits': []},
    '亡': {   'initial': '-',
             'final': 'uang',
             'pinyin': 'wang',
             'tone': 2,
             'splits': []},
    '门': {   'initial': 'm',
             'final': 'en',
             'pinyin': 'men',
             'tone': 2,
             'splits': []},
    '丫': {   'initial': '-',
             'final': 'ia',
             'pinyin': 'ya',
             'tone': 1,
             'splits': []},
    '义': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 4,
             'splits': []},
    '之': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 1,
             'splits': []},
    '尸': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 1,
             'splits': []},
    '己': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 3,
             'splits': []},
    '已': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 3,
             'splits': []},
    '巳': {   'initial': 's',
             'final': 'ih',
             'pinyin': 'si',
             'tone': 4,
             'splits': []},
    '弓': {   'initial': 'g',
             'final': 'ong',
             'pinyin': 'gong',
             'tone': 1,
             'splits': []},
    '子': {   'initial': 'z',
             'final': 'ih',
             'pinyin': 'zi',
             'tone': 3,
             'splits': []},
    '卫': {   'initial': '-',
             'final': 'uei',
             'pinyin': 'wei',
             'tone': 4,
             'splits': []},
    '也': {   'initial': '-',
             'final': 'ie',
             'pinyin': 'ye',
             'tone': 3,
             'splits': []},
    '刃': {   'initial': 'r',
             'final': 'en',
             'pinyin': 'ren',
             'tone': 4,
             'splits': []},
    '飞': {   'initial': 'f',
             'final': 'ei',
             'pinyin': 'fei',
             'tone': 1,
             'splits': []},
    '习': {   'initial': 'x',
             'final': 'i',
             'pinyin': 'xi',
             'tone': 2,
             'splits': []},
    '叉': {   'initial': 'ch',
             'final': 'a',
             'pinyin': 'cha',
             'tone': 1,
             'splits': []},
    '乡': {   'initial': 'x',
             'final': 'iang',
             'pinyin': 'xiang',
             'tone': 1,
             'splits': []},
    '丰': {   'initial': 'f',
             'final': 'eng',
             'pinyin': 'feng',
             'tone': 1,
             'splits': []},
    '王': {   'initial': '-',
             'final': 'uang',
             'pinyin': 'wang',
             'tone': 2,
             'splits': []},
    '开': {   'initial': 'k',
             'final': 'ai',
             'pinyin': 'kai',
             'tone': 1,
             'splits': []},
    '井': {   'initial': 'j',
             'final': 'ing',
             'pinyin': 'jing',
             'tone': 3,
             'splits': []},
    '天': {   'initial': 't',
             'final': 'ian',
             'pinyin': 'tian',
             'tone': 1,
             'splits': []},
    '夫': {   'initial': 'f',
             'final': 'u',
             'pinyin': 'fu',
             'tone': 1,
             'splits': []},
    '元': {   'initial': '-',
             'final': 'üan',
             'pinyin': 'yuan',
             'tone': 2,
             'splits': []},
    '无': {   'initial': '-',
             'final': 'u',
             'pinyin': 'wu',
             'tone': 2,
             'splits': []},
    '云': {   'initial': '-',
             'final': 'ün',
             'pinyin': 'yun',
             'tone': 2,
             'splits': []},
    '专': {   'initial': 'zh',
             'final': 'uan',
             'pinyin': 'zhuan',
             'tone': 1,
             'splits': []},
    '丐': {   'initial': 'g',
             'final': 'ai',
             'pinyin': 'gai',
             'tone': 4,
             'splits': []},
    '艺': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 4,
             'splits': []},
    '木': {   'initial': 'm',
             'final': 'u',
             'pinyin': 'mu',
             'tone': 4,
             'splits': []},
    '五': {   'initial': '-',
             'final': 'u',
             'pinyin': 'wu',
             'tone': 3,
             'splits': []},
    '支': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 1,
             'splits': []},
    '厅': {   'initial': 't',
             'final': 'ing',
             'pinyin': 'ting',
             'tone': 1,
             'splits': []},
    '不': {   'initial': 'b',
             'final': 'u',
             'pinyin': 'bu',
             'tone': 4,
             'splits': []},
    '犬': {   'initial': 'q',
             'final': 'üan',
             'pinyin': 'quan',
             'tone': 3,
             'splits': []},
    '太': {   'initial': 't',
             'final': 'ai',
             'pinyin': 'tai',
             'tone': 4,
             'splits': []},
    '区': {   'initial': 'q',
             'final': 'ü',
             'pinyin': 'qu',
             'tone': 1,
             'splits': []},
    '历': {   'initial': 'l',
             'final': 'i',
             'pinyin': 'li',
             'tone': 4,
             'splits': []},
    '歹': {   'initial': 'd',
             'final': 'ai',
             'pinyin': 'dai',
             'tone': 3,
             'splits': []},
    '友': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 3,
             'splits': []},
    '尤': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 2,
             'splits': []},
    '匹': {   'initial': 'p',
             'final': 'i',
             'pinyin': 'pi',
             'tone': 3,
             'splits': []},
    '车': {   'initial': 'ch',
             'final': 'e',
             'pinyin': 'che',
             'tone': 1,
             'splits': []},
    '巨': {   'initial': 'j',
             'final': 'ü',
             'pinyin': 'ju',
             'tone': 4,
             'splits': []},
    '牙': {   'initial': '-',
             'final': 'ia',
             'pinyin': 'ya',
             'tone': 2,
             'splits': []},
    '戈': {   'initial': 'g',
             'final': 'e',
             'pinyin': 'ge',
             'tone': 1,
             'splits': []},
    '比': {   'initial': 'b',
             'final': 'i',
             'pinyin': 'bi',
             'tone': 3,
             'splits': []},
    '互': {   'initial': 'h',
             'final': 'u',
             'pinyin': 'hu',
             'tone': 4,
             'splits': []},
    '瓦': {   'initial': '-',
             'final': 'ua',
             'pinyin': 'wa',
             'tone': 3,
             'splits': []},
    '止': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 3,
             'splits': []},
    '曰': {   'initial': '-',
             'final': 'üe',
             'pinyin': 'yue',
             'tone': 1,
             'splits': []},
    '日': {   'initial': 'r',
             'final': 'ih',
             'pinyin': 'ri',
             'tone': 4,
             'splits': []},
    '贝': {   'initial': 'b',
             'final': 'ei',
             'pinyin': 'bei',
             'tone': 4,
             'splits': []},
    '冈': {   'initial': 'g',
             'final': 'ang',
             'pinyin': 'gang',
             'tone': 1,
             'splits': []},
    '内': {   'initial': 'n',
             'final': 'ei',
             'pinyin': 'nei',
             'tone': 4,
             'splits': []},
    '水': {   'initial': 'sh',
             'final': 'uei',
             'pinyin': 'shui',
             'tone': 3,
             'splits': []},
    '见': {   'initial': 'j',
             'final': 'ian',
             'pinyin': 'jian',
             'tone': 4,
             'splits': []},
    '午': {   'initial': '-',
             'final': 'u',
             'pinyin': 'wu',
             'tone': 3,
             'splits': []},
    '牛': {   'initial': 'n',
             'final': 'iou',
             'pinyin': 'niu',
             'tone': 2,
             'splits': []},
    '手': {   'initial': 'sh',
             'final': 'ou',
             'pinyin': 'shou',
             'tone': 3,
             'splits': []},
    '气': {   'initial': 'q',
             'final': 'i',
             'pinyin': 'qi',
             'tone': 4,
             'splits': []},
    '毛': {   'initial': 'm',
             'final': 'ao',
             'pinyin': 'mao',
             'tone': 2,
             'splits': []},
    '壬': {   'initial': 'r',
             'final': 'en',
             'pinyin': 'ren',
             'tone': 2,
             'splits': []},
    '升': {   'initial': 'sh',
             'final': 'eng',
             'pinyin': 'sheng',
             'tone': 1,
             'splits': []},
    '夭': {   'initial': '-',
             'final': 'iao',
             'pinyin': 'yao',
             'tone': 1,
             'splits': []},
    '片': {   'initial': 'p',
             'final': 'ian',
             'pinyin': 'pian',
             'tone': 4,
             'splits': []},
    '化': {   'initial': 'h',
             'final': 'ua',
             'pinyin': 'hua',
             'tone': 4,
             'splits': []},
    '仇': {   'initial': 'ch',
             'final': 'ou',
             'pinyin': 'chou',
             'tone': 2,
             'splits': []},
    '币': {   'initial': 'b',
             'final': 'i',
             'pinyin': 'bi',
             'tone': 4,
             'splits': []},
    '仍': {   'initial': 'r',
             'final': 'eng',
             'pinyin': 'reng',
             'tone': 2,
             'splits': []},
    '仅': {   'initial': 'j',
             'final': 'in',
             'pinyin': 'jin',
             'tone': 3,
             'splits': []},
    '斤': {   'initial': 'j',
             'final': 'in',
             'pinyin': 'jin',
             'tone': 1,
             'splits': []},
    '爪': {   'initial': 'zh',
             'final': 'ua',
             'pinyin': 'zhua',
             'tone': 3,
             'splits': []},
    '反': {   'initial': 'f',
             'final': 'an',
             'pinyin': 'fan',
             'tone': 3,
             'splits': []},
    '介': {   'initial': 'j',
             'final': 'ie',
             'pinyin': 'jie',
             'tone': 4,
             'splits': []},
    '父': {   'initial': 'f',
             'final': 'u',
             'pinyin': 'fu',
             'tone': 4,
             'splits': []},
    '从': {   'initial': 'c',
             'final': 'ong',
             'pinyin': 'cong',
             'tone': 2,
             'splits': []},
    '仑': {   'initial': 'l',
             'final': 'uen',
             'pinyin': 'lun',
             'tone': 2,
             'splits': []},
    '今': {   'initial': 'j',
             'final': 'in',
             'pinyin': 'jin',
             'tone': 1,
             'splits': []},
    '凶': {   'initial': 'x',
             'final': 'iong',
             'pinyin': 'xiong',
             'tone': 1,
             'splits': []},
    '乏': {   'initial': 'f',
             'final': 'a',
             'pinyin': 'fa',
             'tone': 2,
             'splits': []},
    '公': {   'initial': 'g',
             'final': 'ong',
             'pinyin': 'gong',
             'tone': 1,
             'splits': []},
    '仓': {   'initial': 'c',
             'final': 'ang',
             'pinyin': 'cang',
             'tone': 1,
             'splits': []},
    '月': {   'initial': '-',
             'final': 'üe',
             'pinyin': 'yue',
             'tone': 4,
             'splits': []},
    '氏': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 4,
             'splits': []},
    '勿': {   'initial': '-',
             'final': 'u',
             'pinyin': 'wu',
             'tone': 4,
             'splits': []},
    '欠': {   'initial': 'q',
             'final': 'ian',
             'pinyin': 'qian',
             'tone': 4,
             'splits': []},
    '风': {   'initial': 'f',
             'final': 'eng',
             'pinyin': 'feng',
             'tone': 1,
             'splits': []},
    '丹': {   'initial': 'd',
             'final': 'an',
             'pinyin': 'dan',
             'tone': 1,
             'splits': []},
    '匀': {   'initial': '-',
             'final': 'ün',
             'pinyin': 'yun',
             'tone': 2,
             'splits': []},
    '勾': {   'initial': 'g',
             'final': 'ou',
             'pinyin': 'gou',
             'tone': 1,
             'splits': []},
    '凤': {   'initial': 'f',
             'final': 'eng',
             'pinyin': 'feng',
             'tone': 4,
             'splits': []},
    '六': {   'initial': 'l',
             'final': 'iou',
             'pinyin': 'liu',
             'tone': 4,
             'splits': []},
    '文': {   'initial': '-',
             'final': 'uen',
             'pinyin': 'wen',
             'tone': 2,
             'splits': []},
    '亢': {   'initial': 'k',
             'final': 'ang',
             'pinyin': 'kang',
             'tone': 4,
             'splits': []},
    '方': {   'initial': 'f',
             'final': 'ang',
             'pinyin': 'fang',
             'tone': 1,
             'splits': []},
    '火': {   'initial': 'h',
             'final': 'uo',
             'pinyin': 'huo',
             'tone': 3,
             'splits': []},
    '忆': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 4,
             'splits': []},
    '计': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 4,
             'splits': []},
    '订': {   'initial': 'd',
             'final': 'ing',
             'pinyin': 'ding',
             'tone': 4,
             'splits': []},
    '户': {   'initial': 'h',
             'final': 'u',
             'pinyin': 'hu',
             'tone': 4,
             'splits': []},
    '认': {   'initial': 'r',
             'final': 'en',
             'pinyin': 'ren',
             'tone': 4,
             'splits': []},
    '冗': {   'initial': 'r',
             'final': 'ong',
             'pinyin': 'rong',
             'tone': 3,
             'splits': []},
    '讥': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 1,
             'splits': []},
    '心': {   'initial': 'x',
             'final': 'in',
             'pinyin': 'xin',
             'tone': 1,
             'splits': []},
    '尺': {   'initial': 'ch',
             'final': 'ih',
             'pinyin': 'chi',
             'tone': 3,
             'splits': []},
    '引': {   'initial': '-',
             'final': 'in',
             'pinyin': 'yin',
             'tone': 3,
             'splits': []},
    '丑': {   'initial': 'ch',
             'final': 'ou',
             'pinyin': 'chou',
             'tone': 3,
             'splits': []},
    '巴': {   'initial': 'b',
             'final': 'a',
             'pinyin': 'ba',
             'tone': 1,
             'splits': []},
    '孔': {   'initial': 'k',
             'final': 'ong',
             'pinyin': 'kong',
             'tone': 3,
             'splits': []},
    '队': {   'initial': 'd',
             'final': 'uei',
             'pinyin': 'dui',
             'tone': 4,
             'splits': []},
    '办': {   'initial': 'b',
             'final': 'an',
             'pinyin': 'ban',
             'tone': 4,
             'splits': []},
    '以': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 3,
             'splits': []},
    '允': {   'initial': '-',
             'final': 'ün',
             'pinyin': 'yun',
             'tone': 3,
             'splits': []},
    '予': {   'initial': '-',
             'final': 'ü',
             'pinyin': 'yu',
             'tone': 3,
             'splits': []},
    '邓': {   'initial': 'd',
             'final': 'eng',
             'pinyin': 'deng',
             'tone': 4,
             'splits': []},
    '劝': {   'initial': 'q',
             'final': 'üan',
             'pinyin': 'quan',
             'tone': 4,
             'splits': []},
    '双': {   'initial': 'sh',
             'final': 'uang',
             'pinyin': 'shuang',
             'tone': 1,
             'splits': []},
    '书': {   'initial': 'sh',
             'final': 'u',
             'pinyin': 'shu',
             'tone': 1,
             'splits': []},
    '幻': {   'initial': 'h',
             'final': 'uan',
             'pinyin': 'huan',
             'tone': 4,
             'splits': []},
    '玉': {   'initial': '-',
             'final': 'ü',
             'pinyin': 'yu',
             'tone': 4,
             'splits': []},
    '刊': {   'initial': 'k',
             'final': 'an',
             'pinyin': 'kan',
             'tone': 1,
             'splits': []},
    '未': {   'initial': '-',
             'final': 'uei',
             'pinyin': 'wei',
             'tone': 4,
             'splits': []},
    '末': {   'initial': 'm',
             'final': 'o',
             'pinyin': 'mo',
             'tone': 4,
             'splits': []},
    '示': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 4,
             'splits': []},
    '击': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 1,
             'splits': []},
    '巧': {   'initial': 'q',
             'final': 'iao',
             'pinyin': 'qiao',
             'tone': 3,
             'splits': []},
    '扑': {   'initial': 'p',
             'final': 'u',
             'pinyin': 'pu',
             'tone': 1,
             'splits': []},
    '功': {   'initial': 'g',
             'final': 'ong',
             'pinyin': 'gong',
             'tone': 1,
             'splits': []},
    '扔': {   'initial': 'r',
             'final': 'eng',
             'pinyin': 'reng',
             'tone': 1,
             'splits': []},
    '去': {   'initial': 'q',
             'final': 'ü',
             'pinyin': 'qu',
             'tone': 4,
             'splits': []},
    '甘': {   'initial': 'g',
             'final': 'an',
             'pinyin': 'gan',
             'tone': 1,
             'splits': []},
    '世': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 4,
             'splits': []},
    '艾': {   'initial': '-',
             'final': 'ai',
             'pinyin': 'ai',
             'tone': 4,
             'splits': []},
    '古': {   'initial': 'g',
             'final': 'u',
             'pinyin': 'gu',
             'tone': 3,
             'splits': []},
    '节': {   'initial': 'j',
             'final': 'ie',
             'pinyin': 'jie',
             'tone': 2,
             'splits': []},
    '本': {   'initial': 'b',
             'final': 'en',
             'pinyin': 'ben',
             'tone': 3,
             'splits': []},
    '术': {   'initial': 'sh',
             'final': 'u',
             'pinyin': 'shu',
             'tone': 4,
             'splits': []},
    '可': {   'initial': 'k',
             'final': 'e',
             'pinyin': 'ke',
             'tone': 3,
             'splits': []},
    '丙': {   'initial': 'b',
             'final': 'ing',
             'pinyin': 'bing',
             'tone': 3,
             'splits': []},
    '左': {   'initial': 'z',
             'final': 'uo',
             'pinyin': 'zuo',
             'tone': 3,
             'splits': []},
    '厉': {   'initial': 'l',
             'final': 'i',
             'pinyin': 'li',
             'tone': 4,
             'splits': []},
    '石': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 2,
             'splits': []},
    '右': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 4,
             'splits': []},
    '布': {   'initial': 'b',
             'final': 'u',
             'pinyin': 'bu',
             'tone': 4,
             'splits': []},
    '夯': {   'initial': 'h',
             'final': 'ang',
             'pinyin': 'hang',
             'tone': 1,
             'splits': []},
    '戊': {   'initial': '-',
             'final': 'u',
             'pinyin': 'wu',
             'tone': 4,
             'splits': []},
    '龙': {   'initial': 'l',
             'final': 'ong',
             'pinyin': 'long',
             'tone': 2,
             'splits': []},
    '平': {   'initial': 'p',
             'final': 'ing',
             'pinyin': 'ping',
             'tone': 2,
             'splits': []},
    '灭': {   'initial': 'm',
             'final': 'ie',
             'pinyin': 'mie',
             'tone': 4,
             'splits': []},
    '东': {   'initial': 'd',
             'final': 'ong',
             'pinyin': 'dong',
             'tone': 1,
             'splits': []},
    '北': {   'initial': 'b',
             'final': 'ei',
             'pinyin': 'bei',
             'tone': 3,
             'splits': []},
    '凸': {   'initial': 't',
             'final': 'u',
             'pinyin': 'tu',
             'tone': 1,
             'splits': []},
    '卢': {   'initial': 'l',
             'final': 'u',
             'pinyin': 'lu',
             'tone': 2,
             'splits': []},
    '业': {   'initial': '-',
             'final': 'ie',
             'pinyin': 'ye',
             'tone': 4,
             'splits': []},
    '旧': {   'initial': 'j',
             'final': 'iou',
             'pinyin': 'jiu',
             'tone': 4,
             'splits': []},
    '帅': {   'initial': 'sh',
             'final': 'uai',
             'pinyin': 'shuai',
             'tone': 4,
             'splits': []},
    '归': {   'initial': 'g',
             'final': 'uei',
             'pinyin': 'gui',
             'tone': 1,
             'splits': []},
    '旦': {   'initial': 'd',
             'final': 'an',
             'pinyin': 'dan',
             'tone': 4,
             'splits': []},
    '目': {   'initial': 'm',
             'final': 'u',
             'pinyin': 'mu',
             'tone': 4,
             'splits': []},
    '且': {   'initial': 'q',
             'final': 'ie',
             'pinyin': 'qie',
             'tone': 3,
             'splits': []},
    '叶': {   'initial': '-',
             'final': 'ie',
             'pinyin': 'ye',
             'tone': 4,
             'splits': []},
    '甲': {   'initial': 'j',
             'final': 'ia',
             'pinyin': 'jia',
             'tone': 3,
             'splits': []},
    '申': {   'initial': 'sh',
             'final': 'en',
             'pinyin': 'shen',
             'tone': 1,
             'splits': []},
    '叮': {   'initial': 'd',
             'final': 'ing',
             'pinyin': 'ding',
             'tone': 1,
             'splits': []},
    '电': {   'initial': 'd',
             'final': 'ian',
             'pinyin': 'dian',
             'tone': 4,
             'splits': []},
    '号': {   'initial': 'h',
             'final': 'ao',
             'pinyin': 'hao',
             'tone': 4,
             'splits': []},
    '田': {   'initial': 't',
             'final': 'ian',
             'pinyin': 'tian',
             'tone': 2,
             'splits': []},
    '由': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 2,
             'splits': []},
    '叭': {   'initial': 'b',
             'final': 'a',
             'pinyin': 'ba',
             'tone': 1,
             'splits': []},
    '史': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 3,
             'splits': []},
    '央': {   'initial': '-',
             'final': 'iang',
             'pinyin': 'yang',
             'tone': 1,
             'splits': []},
    '兄': {   'initial': 'x',
             'final': 'iong',
             'pinyin': 'xiong',
             'tone': 1,
             'splits': []},
    '叽': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 1,
             'splits': []},
    '叼': {   'initial': 'd',
             'final': 'iao',
             'pinyin': 'diao',
             'tone': 1,
             'splits': []},
    '叫': {   'initial': 'j',
             'final': 'iao',
             'pinyin': 'jiao',
             'tone': 4,
             'splits': []},
    '叩': {   'initial': 'k',
             'final': 'ou',
             'pinyin': 'kou',
             'tone': 4,
             'splits': []},
    '叨': {   'initial': 'd',
             'final': 'ao',
             'pinyin': 'dao',
             'tone': 1,
             'splits': []},
    '另': {   'initial': 'l',
             'final': 'ing',
             'pinyin': 'ling',
             'tone': 4,
             'splits': []},
    '叹': {   'initial': 't',
             'final': 'an',
             'pinyin': 'tan',
             'tone': 4,
             'splits': []},
    '冉': {   'initial': 'r',
             'final': 'an',
             'pinyin': 'ran',
             'tone': 3,
             'splits': []},
    '皿': {   'initial': 'm',
             'final': 'in',
             'pinyin': 'min',
             'tone': 3,
             'splits': []},
    '凹': {   'initial': '-',
             'final': 'ao',
             'pinyin': 'ao',
             'tone': 1,
             'splits': []},
    '囚': {   'initial': 'q',
             'final': 'iou',
             'pinyin': 'qiu',
             'tone': 2,
             'splits': []},
    '四': {   'initial': 's',
             'final': 'ih',
             'pinyin': 'si',
             'tone': 4,
             'splits': []},
    '生': {   'initial': 'sh',
             'final': 'eng',
             'pinyin': 'sheng',
             'tone': 1,
             'splits': []},
    '矢': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 3,
             'splits': []},
    '失': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 1,
             'splits': []},
    '乍': {   'initial': 'zh',
             'final': 'a',
             'pinyin': 'zha',
             'tone': 4,
             'splits': []},
    '禾': {   'initial': 'h',
             'final': 'e',
             'pinyin': 'he',
             'tone': 2,
             'splits': []},
    '丘': {   'initial': 'q',
             'final': 'iou',
             'pinyin': 'qiu',
             'tone': 1,
             'splits': []},
    '付': {   'initial': 'f',
             'final': 'u',
             'pinyin': 'fu',
             'tone': 4,
             'splits': []},
    '仗': {   'initial': 'zh',
             'final': 'ang',
             'pinyin': 'zhang',
             'tone': 4,
             'splits': []},
    '代': {   'initial': 'd',
             'final': 'ai',
             'pinyin': 'dai',
             'tone': 4,
             'splits': []},
    '仙': {   'initial': 'x',
             'final': 'ian',
             'pinyin': 'xian',
             'tone': 1,
             'splits': []},
    '仪': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 2,
             'splits': []},
    '白': {   'initial': 'b',
             'final': 'ai',
             'pinyin': 'bai',
             'tone': 2,
             'splits': []},
    '他': {   'initial': 't',
             'final': 'a',
             'pinyin': 'ta',
             'tone': 1,
             'splits': []},
    '斥': {   'initial': 'ch',
             'final': 'ih',
             'pinyin': 'chi',
             'tone': 4,
             'splits': []},
    '瓜': {   'initial': 'g',
             'final': 'ua',
             'pinyin': 'gua',
             'tone': 1,
             'splits': []},
    '乎': {   'initial': 'h',
             'final': 'u',
             'pinyin': 'hu',
             'tone': 1,
             'splits': []},
    '丛': {   'initial': 'c',
             'final': 'ong',
             'pinyin': 'cong',
             'tone': 2,
             'splits': []},
    '令': {   'initial': 'l',
             'final': 'ing',
             'pinyin': 'ling',
             'tone': 4,
             'splits': []},
    '用': {   'initial': '-',
             'final': 'iong',
             'pinyin': 'yong',
             'tone': 4,
             'splits': []},
    '甩': {   'initial': 'sh',
             'final': 'uai',
             'pinyin': 'shuai',
             'tone': 3,
             'splits': []},
    '印': {   'initial': '-',
             'final': 'in',
             'pinyin': 'yin',
             'tone': 4,
             'splits': []},
    '尔': {   'initial': '-',
             'final': 'er',
             'pinyin': 'er',
             'tone': 3,
             'splits': []},
    '句': {   'initial': 'j',
             'final': 'ü',
             'pinyin': 'ju',
             'tone': 4,
             'splits': []},
    '匆': {   'initial': 'c',
             'final': 'ong',
             'pinyin': 'cong',
             'tone': 1,
             'splits': []},
    '册': {   'initial': 'c',
             'final': 'e',
             'pinyin': 'ce',
             'tone': 4,
             'splits': []},
    '卯': {   'initial': 'm',
             'final': 'ao',
             'pinyin': 'mao',
             'tone': 3,
             'splits': []},
    '犯': {   'initial': 'f',
             'final': 'an',
             'pinyin': 'fan',
             'tone': 4,
             'splits': []},
    '外': {   'initial': '-',
             'final': 'uai',
             'pinyin': 'wai',
             'tone': 4,
             'splits': []},
    '冬': {   'initial': 'd',
             'final': 'ong',
             'pinyin': 'dong',
             'tone': 1,
             'splits': []},
    '鸟': {   'initial': 'n',
             'final': 'iao',
             'pinyin': 'niao',
             'tone': 3,
             'splits': []},
    '务': {   'initial': '-',
             'final': 'u',
             'pinyin': 'wu',
             'tone': 4,
             'splits': []},
    '包': {   'initial': 'b',
             'final': 'ao',
             'pinyin': 'bao',
             'tone': 1,
             'splits': []},
    '饥': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 1,
             'splits': []},
    '主': {   'initial': 'zh',
             'final': 'u',
             'pinyin': 'zhu',
             'tone': 3,
             'splits': []},
    '市': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 4,
             'splits': []},
    '立': {   'initial': 'l',
             'final': 'i',
             'pinyin': 'li',
             'tone': 4,
             'splits': []},
    '冯': {   'initial': 'f',
             'final': 'eng',
             'pinyin': 'feng',
             'tone': 2,
             'splits': []},
    '玄': {   'initial': 'x',
             'final': 'üan',
             'pinyin': 'xuan',
             'tone': 2,
             'splits': []},
    '闪': {   'initial': 'sh',
             'final': 'an',
             'pinyin': 'shan',
             'tone': 3,
             'splits': []},
    '兰': {   'initial': 'l',
             'final': 'an',
             'pinyin': 'lan',
             'tone': 2,
             'splits': []},
    '半': {   'initial': 'b',
             'final': 'an',
             'pinyin': 'ban',
             'tone': 4,
             'splits': []},
    '汁': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 1,
             'splits': []},
    '汇': {   'initial': 'h',
             'final': 'uei',
             'pinyin': 'hui',
             'tone': 4,
             'splits': []},
    '头': {   'initial': 't',
             'final': 'ou',
             'pinyin': 'tou',
             'tone': 2,
             'splits': []},
    '汉': {   'initial': 'h',
             'final': 'an',
             'pinyin': 'han',
             'tone': 4,
             'splits': []},
    '穴': {   'initial': 'x',
             'final': 'üe',
             'pinyin': 'xue',
             'tone': 2,
             'splits': []},
    '它': {   'initial': 't',
             'final': 'a',
             'pinyin': 'ta',
             'tone': 1,
             'splits': []},
    '讨': {   'initial': 't',
             'final': 'ao',
             'pinyin': 'tao',
             'tone': 3,
             'splits': []},
    '写': {   'initial': 'x',
             'final': 'ie',
             'pinyin': 'xie',
             'tone': 3,
             'splits': []},
    '让': {   'initial': 'r',
             'final': 'ang',
             'pinyin': 'rang',
             'tone': 4,
             'splits': []},
    '礼': {   'initial': 'l',
             'final': 'i',
             'pinyin': 'li',
             'tone': 3,
             'splits': []},
    '训': {   'initial': 'x',
             'final': 'ün',
             'pinyin': 'xun',
             'tone': 4,
             'splits': []},
    '议': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 4,
             'splits': []},
    '必': {   'initial': 'b',
             'final': 'i',
             'pinyin': 'bi',
             'tone': 4,
             'splits': []},
    '讯': {   'initial': 'x',
             'final': 'ün',
             'pinyin': 'xun',
             'tone': 4,
             'splits': []},
    '记': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 4,
             'splits': []},
    '永': {   'initial': '-',
             'final': 'iong',
             'pinyin': 'yong',
             'tone': 3,
             'splits': []},
    '司': {   'initial': 's',
             'final': 'ih',
             'pinyin': 'si',
             'tone': 1,
             'splits': []},
    '民': {   'initial': 'm',
             'final': 'in',
             'pinyin': 'min',
             'tone': 2,
             'splits': []},
    '弗': {   'initial': 'f',
             'final': 'u',
             'pinyin': 'fu',
             'tone': 2,
             'splits': []},
    '弘': {   'initial': 'h',
             'final': 'ong',
             'pinyin': 'hong',
             'tone': 2,
             'splits': []},
    '出': {   'initial': 'ch',
             'final': 'u',
             'pinyin': 'chu',
             'tone': 1,
             'splits': []},
    '辽': {   'initial': 'l',
             'final': 'iao',
             'pinyin': 'liao',
             'tone': 2,
             'splits': []},
    '奶': {   'initial': 'n',
             'final': 'ai',
             'pinyin': 'nai',
             'tone': 3,
             'splits': []},
    '奴': {   'initial': 'n',
             'final': 'u',
             'pinyin': 'nu',
             'tone': 2,
             'splits': []},
    '加': {   'initial': 'j',
             'final': 'ia',
             'pinyin': 'jia',
             'tone': 1,
             'splits': []},
    '皮': {   'initial': 'p',
             'final': 'i',
             'pinyin': 'pi',
             'tone': 2,
             'splits': []},
    '边': {   'initial': 'b',
             'final': 'ian',
             'pinyin': 'bian',
             'tone': 1,
             'splits': []},
    '圣': {   'initial': 'sh',
             'final': 'eng',
             'pinyin': 'sheng',
             'tone': 4,
             'splits': []},
    '对': {   'initial': 'd',
             'final': 'uei',
             'pinyin': 'dui',
             'tone': 4,
             'splits': []},
    '台': {   'initial': 't',
             'final': 'ai',
             'pinyin': 'tai',
             'tone': 2,
             'splits': []},
    '矛': {   'initial': 'm',
             'final': 'ao',
             'pinyin': 'mao',
             'tone': 2,
             'splits': []},
    '纠': {   'initial': 'j',
             'final': 'iou',
             'pinyin': 'jiu',
             'tone': 1,
             'splits': []},
    '母': {   'initial': 'm',
             'final': 'u',
             'pinyin': 'mu',
             'tone': 3,
             'splits': []},
    '幼': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 4,
             'splits': []},
    '丝': {   'initial': 's',
             'final': 'ih',
             'pinyin': 'si',
             'tone': 1,
             'splits': []},
    '邦': {   'initial': 'b',
             'final': 'ang',
             'pinyin': 'bang',
             'tone': 1,
             'splits': []},
    '式': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 4,
             'splits': []},
    '迂': {   'initial': '-',
             'final': 'ü',
             'pinyin': 'yu',
             'tone': 1,
             'splits': []},
    '刑': {   'initial': 'x',
             'final': 'ing',
             'pinyin': 'xing',
             'tone': 2,
             'splits': []},
    '戎': {   'initial': 'r',
             'final': 'ong',
             'pinyin': 'rong',
             'tone': 2,
             'splits': []},
    '动': {   'initial': 'd',
             'final': 'ong',
             'pinyin': 'dong',
             'tone': 4,
             'splits': []},
    '寺': {   'initial': 's',
             'final': 'ih',
             'pinyin': 'si',
             'tone': 4,
             'splits': []},
    '吉': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 2,
             'splits': []},
    '扣': {   'initial': 'k',
             'final': 'ou',
             'pinyin': 'kou',
             'tone': 4,
             'splits': []},
    '考': {   'initial': 'k',
             'final': 'ao',
             'pinyin': 'kao',
             'tone': 3,
             'splits': []},
    '托': {   'initial': 't',
             'final': 'uo',
             'pinyin': 'tuo',
             'tone': 1,
             'splits': []},
    '老': {   'initial': 'l',
             'final': 'ao',
             'pinyin': 'lao',
             'tone': 3,
             'splits': []},
    '巩': {   'initial': 'g',
             'final': 'ong',
             'pinyin': 'gong',
             'tone': 3,
             'splits': []},
    '执': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 2,
             'splits': []},
    '扩': {   'initial': 'k',
             'final': 'uo',
             'pinyin': 'kuo',
             'tone': 4,
             'splits': []},
    '扬': {   'initial': '-',
             'final': 'iang',
             'pinyin': 'yang',
             'tone': 2,
             'splits': []},
    '耳': {   'initial': '-',
             'final': 'er',
             'pinyin': 'er',
             'tone': 3,
             'splits': []},
    '芋': {   'initial': '-',
             'final': 'ü',
             'pinyin': 'yu',
             'tone': 4,
             'splits': []},
    '共': {   'initial': 'g',
             'final': 'ong',
             'pinyin': 'gong',
             'tone': 4,
             'splits': []},
    '芒': {   'initial': 'm',
             'final': 'ang',
             'pinyin': 'mang',
             'tone': 2,
             'splits': []},
    '亚': {   'initial': '-',
             'final': 'ia',
             'pinyin': 'ya',
             'tone': 4,
             'splits': []},
    '芝': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 1,
             'splits': []},
    '朽': {   'initial': 'x',
             'final': 'iou',
             'pinyin': 'xiu',
             'tone': 3,
             'splits': []},
    '机': {   'initial': 'j',
             'final': 'i',
             'pinyin': 'ji',
             'tone': 1,
             'splits': []},
    '权': {   'initial': 'q',
             'final': 'üan',
             'pinyin': 'quan',
             'tone': 2,
             'splits': []},
    '过': {   'initial': 'g',
             'final': 'uo',
             'pinyin': 'guo',
             'tone': 4,
             'splits': []},
    '臣': {   'initial': 'ch',
             'final': 'en',
             'pinyin': 'chen',
             'tone': 2,
             'splits': []},
    '吏': {   'initial': 'l',
             'final': 'i',
             'pinyin': 'li',
             'tone': 4,
             'splits': []},
    '再': {   'initial': 'z',
             'final': 'ai',
             'pinyin': 'zai',
             'tone': 4,
             'splits': []},
    '协': {   'initial': 'x',
             'final': 'ie',
             'pinyin': 'xie',
             'tone': 2,
             'splits': []},
    '西': {   'initial': 'x',
             'final': 'i',
             'pinyin': 'xi',
             'tone': 1,
             'splits': []},
    '厌': {   'initial': '-',
             'final': 'ian',
             'pinyin': 'yan',
             'tone': 4,
             'splits': []},
    '戌': {   'initial': 'x',
             'final': 'ü',
             'pinyin': 'xu',
             'tone': 1,
             'splits': []},
    '在': {   'initial': 'z',
             'final': 'ai',
             'pinyin': 'zai',
             'tone': 4,
             'splits': []},
    '百': {   'initial': 'b',
             'final': 'ai',
             'pinyin': 'bai',
             'tone': 3,
             'splits': []},
    '有': {   'initial': '-',
             'final': 'iou',
             'pinyin': 'you',
             'tone': 3,
             'splits': []},
    '存': {   'initial': 'c',
             'final': 'uen',
             'pinyin': 'cun',
             'tone': 2,
             'splits': []},
    '而': {   'initial': '-',
             'final': 'er',
             'pinyin': 'er',
             'tone': 2,
             'splits': []},
    '页': {   'initial': '-',
             'final': 'ie',
             'pinyin': 'ye',
             'tone': 4,
             'splits': []},
    '匠': {   'initial': 'j',
             'final': 'iang',
             'pinyin': 'jiang',
             'tone': 4,
             'splits': []},
    '夸': {   'initial': 'k',
             'final': 'ua',
             'pinyin': 'kua',
             'tone': 1,
             'splits': []},
    '夺': {   'initial': 'd',
             'final': 'uo',
             'pinyin': 'duo',
             'tone': 2,
             'splits': []},
    '灰': {   'initial': 'h',
             'final': 'uei',
             'pinyin': 'hui',
             'tone': 1,
             'splits': []},
    '达': {   'initial': 'd',
             'final': 'a',
             'pinyin': 'da',
             'tone': 2,
             'splits': []},
    '列': {   'initial': 'l',
             'final': 'ie',
             'pinyin': 'lie',
             'tone': 4,
             'splits': []},
    '死': {   'initial': 's',
             'final': 'ih',
             'pinyin': 'si',
             'tone': 3,
             'splits': []},
    '成': {   'initial': 'ch',
             'final': 'eng',
             'pinyin': 'cheng',
             'tone': 2,
             'splits': []},
    '夷': {   'initial': '-',
             'final': 'i',
             'pinyin': 'yi',
             'tone': 2,
             'splits': []},
    '轨': {   'initial': 'g',
             'final': 'uei',
             'pinyin': 'gui',
             'tone': 3,
             'splits': []},
    '邪': {   'initial': 'x',
             'final': 'ie',
             'pinyin': 'xie',
             'tone': 2,
             'splits': []},
    '尧': {   'initial': '-',
             'final': 'iao',
             'pinyin': 'yao',
             'tone': 2,
             'splits': []},
    '迈': {   'initial': 'm',
             'final': 'ai',
             'pinyin': 'mai',
             'tone': 4,
             'splits': []},
    '毕': {   'initial': 'b',
             'final': 'i',
             'pinyin': 'bi',
             'tone': 4,
             'splits': []},
    '至': {   'initial': 'zh',
             'final': 'ih',
             'pinyin': 'zhi',
             'tone': 4,
             'splits': []},
    '此': {   'initial': 'c',
             'final': 'ih',
             'pinyin': 'ci',
             'tone': 3,
             'splits': []},
    '贞': {   'initial': 'zh',
             'final': 'en',
             'pinyin': 'zhen',
             'tone': 1,
             'splits': []},
    '师': {   'initial': 'sh',
             'final': 'ih',
             'pinyin': 'shi',
             'tone': 1,
             'splits': []},
    '尘': {   'initial': 'ch',
             'final': 'en',
             'pinyin': 'chen',
             'tone': 2,
             'splits': []},
    '尖': {   'initial': 'j',
             'final': 'ian',
             'pinyin': 'jian',
             'tone': 1,
             'splits': []},
    '劣': {   'initial': 'l',
             'final': 'ie',
             'pinyin': 'lie',
             'tone': 4,
             'splits': []},
    '光': {   'initial': 'g',
             'final': 'uang',
             'pinyin': 'guang',
             'tone': 1,
             'splits': []},
    '早': {   'initial': 'z',
             'final': 'ao',
             'pinyin': 'zao',
             'tone': 3,
             'splits': []},
    '虫': {   'initial': 'ch',
             'final': 'ong',
             'pinyin': 'chong',
             'tone': 2,
             'splits': []},
    '团': {   'initial': 't',
             'final': 'uan',
             'pinyin': 'tuan',
             'tone': 2,
             'splits': []},
    '同': {   'initial': 't',
             'final': 'ong',
             'pinyin': 'tong',
             'tone': 2,
             'splits': []},
    '吊': {   'initial': 'd',
             'final': 'iao',
             'pinyin': 'diao',
             'tone': 4,
             'splits': []},
    '吃': {   'initial': 'ch',
             'final': 'ih',
             'pinyin': 'chi',
             'tone': 1,
             'splits': []},
    '因': {   'initial': '-',
             'final': 'in',
             'pinyin': 'yin',
             'tone': 1,
             'splits': []}}
